CREATE TABLE topics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    message text NOT NULL,
    course_name VARCHAR(100) NOT NULL,
    user_id bigint,
    FOREIGN KEY (user_id) REFERENCES users(id)
);